function fromArray(a) {
  var _i = a.length - 1 | 0;
  var _res = /* [] */0;
  while(true) {
    var res = _res;
    var i = _i;
    if (i < 0) {
      return res;
    }
    _res = {
      hd: a[i],
      tl: res
    };
    _i = i - 1 | 0;
    continue ;
  }}
/* No side effect */

// Generated by ReScript, PLEASE EDIT WITH CARE

function fmod(divident, divisor) {
  return divident - divisor * Math.floor(divident / divisor);
}

function listSum(list) {
  if (list) {
    return list.hd + listSum(list.tl);
  } else {
    return 0;
  }
}

function oddOrEvenFloatArray(array) {
  var arraySum = listSum(fromArray(array));
  var arraySumRemainder = fmod(arraySum, 2);
  return arraySumRemainder === 0;
}

function oddOrEvenJs(array) {
  var match = oddOrEvenFloatArray(array);
  if (match) {
    return "even";
  } else {
    return "odd";
  }
}
/* No side effect */

/* Untyped file generated from Kata1.res by genType. */

const oddOrEven = oddOrEvenJs;

console.log(oddOrEven([1, 2, 3]));
