// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_List from "bs-platform/lib/es6/belt_List.js";

function fmod(divident, divisor) {
  return divident - divisor * Math.floor(divident / divisor);
}

function listSum(list) {
  if (list) {
    return list.hd + listSum(list.tl);
  } else {
    return 0;
  }
}

function oddOrEvenFloatArray(array) {
  var arraySum = listSum(Belt_List.fromArray(array));
  var arraySumRemainder = fmod(arraySum, 2);
  return arraySumRemainder === 0;
}

function oddOrEvenJs(array) {
  var match = oddOrEvenFloatArray(array);
  if (match) {
    return "even";
  } else {
    return "odd";
  }
}

export {
  oddOrEvenFloatArray ,
  oddOrEvenJs ,
  
}
/* No side effect */
