// Generated by ReScript, PLEASE EDIT WITH CARE


function triangular(n) {
  if (n <= 0) {
    return 0;
  } else {
    return n + triangular(n - 1 | 0) | 0;
  }
}

export {
  triangular ,
  
}
/* No side effect */
